name: Hillel Auto e2e test
on: workflow_dispatch

jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps:
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install all dependencies
        run: npm i --force
      - name: Run tests
        run: npm run qaker:run:server
